// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wskosbuvimxntcdfszij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indza29zYnV2aW14bnRjZGZzemlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMjg5MzYsImV4cCI6MjA2ODkwNDkzNn0.qGaxteR56yk_3smuUVGcZnDWfifgGojq6uFkh4judVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});